import REPO_ICON from '@/client/icons/repo.svg';
import { branch, repoName, version } from '@/client/state';

export function Header() {
  return (
    <header>
      <span dangerouslySetInnerHTML={{ __html: REPO_ICON }} />
      <h1>
        {repoName} <span>— Git Heatmap</span>
      </h1>
      <span class="badge">{branch}</span>
    </header>
  );
}

export function Footer() {
  return (
    <footer>
      Generated by <strong>git-heatmap</strong> v{version}
    </footer>
  );
}
